### ISSUE TITLE
Flex新旧语法对比以及项目应用

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#259]
Flex新旧语法对比以及项目应用

box-flex VS flex 
```css
display: box;
```
等于
```css
display: flex;
```
实际项目应该这么写：
```css
div {
    display: -webkit-box;      
    dispaly: box;
    display: -webkit-flex;   
    display: flex
}
```

box-flex VS flex-grow 

```css
box-flex: 1; 
```
等于：

```css
flex-grow：1； //可简写为 flex: 1;
```

实际项目中应该这么写：
```
div {
 -webkit-box-flex: 1;
         box-flex: 1;
  -webkit-flex: 1;
          flex: 1;
}
``` 

**项目实际应用中遵循以上写法，以下列出新语法中旧语法也有的属性**

确定子元素的排列顺序： box-direction VS flex-direction

box-direction可选值有：`normal | reverse `
flex-direction可选值有：`row (normal)| row-reverse | column | column-reverse;`
***
垂直方向上的对齐：box-align VS align-items

box-align可选值有：`start | end | center | baseline | stretch`
align-items可选值有：`flex-start | flex-end | center | baseline | stretch`
***
父标签水平遗留空间的使用：` box-pack VS  justify-content`

box-pack可选属性：`start | end | center | justify`
justify-content可选属性：` flex-start | flex-end | center | space-between | space-around`

目前已知 box-flex VS flex-grow  可通过浏览器测试，剩下的暂时还未测试，实测值后再更新
